INSERT INTO MAISONEDITION(ID, NOM, SIRET)
VALUES (1, 'Maison edition test', 'SIret Test');

INSERT INTO LIVRE(ID, NOM, AUTEUR, DATEPARUTION, ISBN, MAISONEDITION)
VALUES (1, 'nom test', 'AUTEUR TEST', CURRENT_DATE(), 'ISBN TEST', 1);
INSERT INTO LIVRE(ID, NOM, AUTEUR, DATEPARUTION, ISBN, MAISONEDITION)
VALUES (2, 'NOM TEST2', 'AUTEUR TEST2', CURRENT_DATE(), 'ISBN TEST2', 1);
INSERT INTO LIVRE(ID, NOM, AUTEUR, DATEPARUTION, ISBN, MAISONEDITION)
VALUES (3, 'NOM TEST3', 'AUTEUR TEST3', CURRENT_DATE(), 'ISBN TEST3', 1);
INSERT INTO LIVRE(ID, NOM, AUTEUR, DATEPARUTION, ISBN, MAISONEDITION)
VALUES (4, 'NOM TEST4', 'AUTEUR TEST4', CURRENT_DATE(), 'ISBN TEST4', 1);
INSERT INTO LIVRE(ID, NOM, AUTEUR, DATEPARUTION, ISBN, MAISONEDITION)
VALUES (5, 'NOM TEST5', 'AUTEUR TEST5', CURRENT_DATE(), 'ISBN TEST5', 1);